export type Database = {
  public: {
    Tables: {
      fine_tune_snapshots: {
        Row: {
          id: string;
          created_at: string;
          user_id: string;
          uploaded_by: string;
          file_path: string;
          filters: Record<string, any>; // entire filter state stored here
          model_version: string;
          job_status?: string;
          version?: string;
        };
        Insert: {
          id?: string; // if autogenerated
          created_at?: string;
          user_id: string;
          uploaded_by: string;
          file_path: string;
          filters: Record<string, any>;
          model_version: string;
          job_status?: string;
          version?: string;
        };
        Update: Partial<Database["public"]["Tables"]["fine_tune_snapshots"]["Insert"]>;
      };
    };
  };
};
