export type EmotionTrainingRow = {
  source_type: string;
  source_id: string;
  session_id: string;
  session_title: string;
  user_id: string | null;
  full_name: string;
  message_role: string;
  content: string;
  emotion: string;
  original_emotion: string;
  original_intensity: string;
  original_tone: string;
  original_topic: string;
  tone: string;
  intensity: number;
  topic: string | null;
  note: string | null;
  annotation_updated_at: string | null;
  annotation_updated_by: string | null;
  therapist_name: string | null;
  tagged_at: string;
  score: number;
  flagged: boolean;
  flag_reason: string;
  goal: string;
  alignment_score: number;
};
