export type EmotionTrainingRow = {
  source_type: string;
  source_id: string;
  session_id: string;
  session_title: string;
  session_created_at: string;
  session_order_index: string;
  user_id: string | null;
  full_name: string;
  message_role: string;
  content: string;
  emotion: string;
  original_emotion: string;
  original_intensity: string;
  original_tone: string;
  original_topic: string;
  tone: string;
  intensity: number;
  topic: string | null;
  note: string | null;
  annotation_updated_at: string | null;
  annotation_updated_by: string | null;
  annotation_updated_by_name: string | null;
  tagged_at: string;
  score: number;
  flagged: boolean;
  flag_reason: string;
  goal: string;
  alignment_score: number;
  reviewed: boolean;
  reviewed_by: string;
  reviewed_by_name: string;
  supporting_therapists: { id: string; name: string }[];
  message_created_at: string;
  treatment_id: string;
  treatment_name: string;
  treatment_status: string;
  treatment_created_at: string;
};
